services:
  container-manager:
    build:
      context: backend
      dockerfile: Dockerfile
    networks:
      - cm
    ports:
      - 8001:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02

  frontend:
    build:
      context: ./editor
      dockerfile: Dockerfile
      target: dev
    networks:
      - cm
      - dpasp-instances
    ports:
      - 8000:80
    volumes:
      - ./editor:/app

networks:
  cm:
    driver: bridge
  dpasp-instances:
    driver: bridge