services:
  container-manager: &cm
    environment:
      - RUNNER_TARGET=dpasp
    build:
      context: backend
      dockerfile: Dockerfile
    profiles:
      - dpasp
    networks:
      - cm
    ports:
      - 8001:80
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /usr/lib/libdevmapper.so.1.02:/usr/lib/libdevmapper.so.1.02

  container-manager-mock:
    <<: *cm
    profiles:
      - mock
    environment:
      - RUNNER_TARGET=mock
    networks:
      cm:
        aliases:
          - container-manager

  frontend:
    build:
      context: ./editor
      dockerfile: Dockerfile
      target: dev
    networks:
      - cm
      - dpasp-instances
    ports:
      - 8000:80
    volumes:
      - ./editor:/app
    env_file:
      - ./editor/.env

networks:
  cm:
    driver: bridge
  dpasp-instances:
    driver: bridge